spring:
  profiles:
    active: dev

server:
  port: 8866

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sms_config?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-idle: 10
    max-active: 20
    max-wait: 10000
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    initSQL: set names utf8mb4
  redis:
    host: 47.93.6.145
    port: 6379
    password: smstest
    pool:
      min-idle: 1
      max-idle: 8
      max-active: 200  
        
application:
  datasource:
    names: sms_gateway
    sms_gateway:
      url: jdbc:mysql://localhost:3306/sms_gateway?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowPublicKeyRetrieval=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-idle: 10
      max-active: 20
      max-wait: 10000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      initSQL: set names utf8mb4

upload:
  excel-dir: C:\Users\ljm\AppData\Local\Temp\